### ISSUE TITLE
LIVE! page

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#163]
the LIVE! page on jb .com needs to be recreated here in Hugo

* [x] embedded Twitch ( consider https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/122)
* [x] embedded IRC
* [x] RTMP, etc stream links
* [x] menu item for LIVE! page
* [x] #233
* [x] #208

**Comment by StefanS-O** [comment]
I already kind of started something, with this config: `config.jblive.toml` that get's deployed here: https://jb-live.codefighters.net/

**Comment by elreydetoda** [comment]
@gerbrent , I love that you added a "meta-issue" tag, so you can group together changes 😁

Also, @StefanS-O while it's probably (didn't check) getting rsync'ed already, is it already configured from the Nginx side? If so, what's the domain + path to get there?

**Comment by kd2flz** [comment]
I'm happy to mess with embedding a juptier.tube livestream on the jblive.jupiterbroadcasting.net page. Not sure what's involved in this, but I'm happy to at least explore the options.

**Comment by reesericci** [comment]
@kd2flz there are a couple issues with embedding jupiter tube as discussed in #122

**Comment by aaronrea** [comment]
Twitch shouldn't be too difficult - [see here](https://github.com/cmendible/cmendible.github.io/blob/172983ce04bde899e8aceec55f4651aab87ef309/layouts/shortcodes/twitch.html)

Kiwi probably similar but I think it might be tied to some existing user account on the kiwi site. 

Sounds like peertube integration will take a bit more work - probably milestone 2

**Comment by reclaimingmytime** [comment]
It seems like there's an issue with the embedded IRC. Sometimes, when I try to connect by clicking on "Start...", I get `Error Connecting (Error: xhr poll error)`.
![image](https://user-images.githubusercontent.com/35609464/183240226-25cec6e9-6b25-49ec-aa5d-058bf9e57823.png)

The browser console shows a 502 error, which is a server-side issue. Before that, I'm getting the error `Access to XMLHttpRequest at 'https://do-a.clients.kiwiirc.com/client/transport/?EIO=3&transport=polling&t=1659773564379-1' from origin 'https://kiwiirc.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I have the same problem with the embedded chat on http://jblive.tv/. This seems like an issue that needs to be fixed by the embedded chat provider.

Does someone else have this issue?

As an alternative, we can swap out the old Kiwi iframe with the "[Kiwi next client](https://kiwiirc.com/nextclient/irc.geekshed.net/?nick=JBLive_?&theme=dark#jupiterbroadcasting)" or the chat at https://bit.ly/jupiterchat

**Comment by reesericci** [comment]
The kiwi next client feels exactly the same to me - I don't see any problem using it on the site.

**Comment by aaronrea** [comment]
I think there's a header we can set to get around that. I'll try to look in to it this weekend

**Comment by reclaimingmytime** [comment]
@aaronrea Did you find something regarding the header?

I don't think there's much we can do on our end. The way I understand the error message, kiwiirc.com is trying to send a request to a subdomain, both of which we don't control, so we can't solve the cross origin error on our end.

What makes it more difficult to troubleshoot is the error doesn't appear every single time. I think switching to a different embedded IRC client might solve the problem.

**Comment by gerbrent** [comment]
Maybe an upstream bug report would do it?

**Comment by gerbrent** [comment]
> switching to a different embedded IRC client might solve the problem.

@reclaimingmytime like your recommended Kiwi Next client........

**Comment by gerbrent** [comment]
> As an alternative, we can swap out the old Kiwi iframe with the "[Kiwi next client](https://kiwiirc.com/nextclient/irc.geekshed.net/?nick=JBLive_?&theme=dark#jupiterbroadcasting)" or the chat at https://bit.ly/jupiterchat

As my vote, I prefer the Kiwi Next client's interface to our https://bit.ly/jupiterchat



## Kiwi Next
![image](https://user-images.githubusercontent.com/7018928/183771893-b68df8ad-22f0-450e-b1d8-7f5403d5f5d2.png)


## Mibbit / https://bit.ly/jupiterchat
![image](https://user-images.githubusercontent.com/7018928/183771959-acb3e88e-3f86-4204-92a2-7bc80810cdaa.png)

**Comment by kd2flz** [comment]
That Kiwi-Next client looks very nice!

**Comment by aaronrea** [comment]
Sorry, haven't had much time this week/end. I didn't realize there was a "next-gen" client. That gets my vote.

**Comment by elreydetoda** [comment]
Closing this out since all tasks are done on this issue :grin: :partying_face: :rocket:
