### ISSUE TITLE
IRC in menu, Community page, footer - leads to a bland page

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#210]
the "IRC" menu item AND card on the [Community page](https://jupiterbroadcasting.net/community/) AND footer item leads to an irc-dedicated page at https://jupiterbroadcasting.net/community/irc/

This page is rather bland.

#### We should either:

A. link directly to [Kiwi IRC](https://kiwiirc.com/client/irc.geekshed.net/?nick=JBLive_?&theme=cli#jupiterbroadcasting)

or...

B. link to the Live! page (#163 ) with the IRC embed.

or...

C. Embed the Kiwi IRC into the ./community/irc page

#### todo:
* [ ] change IRC sub-menu item behaviour
* [ ] change IRC card on [Community page](https://jupiterbroadcasting.net/community/) behaviour
* [ ] change IRC footer link behaviour

thoughts? feedback? preferences?

**Comment by reesericci** [comment]
I think personally that a menu item should link externally to Kiwi

**Comment by reclaimingmytime** [comment]
I think besides linking an IRC web client, we should list the IRC details on the community page. People new to IRC can easily join, and someone with an existing IRC client can see the necessary IRC details.

Maybe we can make the existing link a prettier button and include the IRC details from the live page.
![image](https://user-images.githubusercontent.com/35609464/183223178-fd242cee-45ff-40b9-930d-f5bcb09cb929.png)

**Comment by reclaimingmytime** [comment]
As there seem to be no objections to my idea, I'm going to implement it and create a pull request ;)
