### ISSUE TITLE
Community section

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#24]
* [x] Integrate Community "section"

May include:
* [x] Matrix Server info and connection tutorial -  #13
* [x] Mumble Server info and connection tutorial - #9
* [x] Telegram Group link - #63
* [x] SSH Discord
* meetup.com ?
* more?

Grouping all the above into a  submenu might be helpful for community members, while reducing the # of menu items. I envision  a page dedicated to each of the above tickets/topics. In the case of the Telegram group link, a simple URL redirect menu item may be sufficient.

Another implementation option is the footer, however this becomes less obvious to the eyes of a page visitor since it will necessarily be at the very bottom of a list of recent episodes on the home page. A more prominent location. i.e. the menu, is likely more helpful.

A good question: Where, how to place a show-specific community item such as the SSH Discord?

**Comment by Lord0fBytes** [comment]
Might also be easy enough now to add it to the footer that Stefan created. Looks like some work was already done there.

**Comment by elreydetoda** [comment]
Ya, I was initially thinking that as well, and we can probably put all the links there still.

From my interpretation of this though, it sounds like that they want a page so they can put helpful information (notes/video walk-through) on how to connect next to the platform (i.e. mumble & element) as well as the links.

**Comment by gerbrent** [comment]
good ideas both of you!

I was going to tackle this one, considering it's well suited to my skillset and the bulk of the work is rewording the processes in the issues listed above.

And yes, I was thinking grouping all the above into a single page might be helpful. but.... thanks to you both am now reconsidering the approach ; )

**Comment by elreydetoda** [comment]
Awesome, thank you for updating and adding more context 😁

I'll try and work on it tonight, and I'll post here again if I don't get around to it after work 🙃

**Comment by elreydetoda** [comment]
> A good question: Where, how to place a show-specific community item such as the SSH Discord?

Just off the top of my head I could imagine it could be below all the JB network wide comms (maybe grouping them per show if there is more than one), and then also listed on the show specific page as well.
How does that sound?

**Comment by elreydetoda** [comment]
Alright, I just set #129 for ready for review. I don't know if I'll be able to do all of this issue, because my PR covers pretty much all the base framework for this page, menu, and footer.

So, the parts I don't think I'll be able to get to is all the content i.e. the walk-through for matrix and all the smaller details of writing content for each page. I think I should probably start focusing on #110, because that's going to be holding up a few issues if I don't get it done soon.

**Comment by elreydetoda** [comment]
Just so we're on the same page this'll have to be re-opened for the content of walk through or another issue will need to be made (@gerbrent )

**Comment by gerbrent** [comment]
I can handle the content (or someone else if they are willing). @elreydetoda happy to have you work elsewhere, where your skills are multipliers!
