### ISSUE TITLE
Testing `develop` branch workflow

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#432]
Testing part of the workflow for our (soon) eventual move to a [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) workflow to protect main and offer - in the future - live full-production testing of the develop branch.

We'll see if I understand all of this well ; )

Steps for this test:
* [x] do a PR #431  to merge `main` -> `develop` to bring `develop` in sync w `main`
* [x] have someone merge said PR (thanks @elreydetoda !)
* [x] apply PR #400 to `develop`
* [x] see how the E2E Tests do w that one (for fun!). Not expecting anything PR #400 specific other than a green light..
* [x] If satisfied, do a PR from `develop` to `main` #433

**Comment by gerbrent** [comment]
: )

![image](https://user-images.githubusercontent.com/7018928/192647442-846539f0-c637-4892-9c31-30babb6969fb.png)

**Comment by gerbrent** [comment]
One gotcha:

The `develop` branch was auto-deleted on the merge to `main`,  since we have that set. 

![image](https://user-images.githubusercontent.com/7018928/192834184-fe51913b-7f82-4b9a-910c-ea32554593cc.png)

**Comment by elreydetoda** [comment]
> One gotcha:
> 
> The `develop` branch was auto-deleted on the merge to `main`,  since we have that set. 
> 
> ![image](https://user-images.githubusercontent.com/7018928/192834184-fe51913b-7f82-4b9a-910c-ea32554593cc.png)
> 

Just a heads up, this could be prevented with branch protection rules. So while yes I did delete it by accident 😅, if we had branch protection rules on I wouldn't be able to. Only an admin might be able to, unless you required admins to adhere to the protection ( which I recommend you do enable this and unchecked that box when you need to force an action that's being blocked).
