### ISSUE TITLE
JB & Hacktoberfest - Let's participate!

### ISSUE THREAD

**Issue by reesericci** [JupiterBroadcasting/jupiterbroadcasting.com#457]
It would be cool if JB would add the "hacktoberfest" tag to this repo so contributors can get credit for submitting PRs for [Hacktoberfest](https://hacktoberfest.com)!

**Comment by gerbrent** [comment]
actions taken as suggested by https://hacktoberfest.com/participation/#maintainers

* `hacktoberfest` label created
* `hacktoberfest-accepted` label created and should be applied to any `hacktoberfest`-labeled issues/PRs

## Todo
* identify good hacktoberfest tickets to solve! - please feel free to recommend some that might fit and/or while you're working on a PR

**Comment by CGBassPlayer** [comment]
I think anything issues that are a `good first issue` would be a good start. But I'll look through and see what would be good as well

**Comment by gerbrent** [comment]
## Contributors
Here’s what you need to know to participate and complete Hacktoberfest:

* [ ] [Register](https://hacktoberfest.com/auth/) anytime between September 26 and October 31

* [ ] Pull requests can be made in any [GitHub](https://github.com/topics/hacktoberfest) or [GitLab](https://gitlab.com/explore/projects/topics/hacktoberfest) hosted project that’s participating in Hacktoberfest (look for the “hacktoberfest” topic)

* [ ] Project maintainers must accept your pull/merge requests for them to count toward your total
* [ ] Have 4 pull/merge requests accepted between October 1 and October 31 to complete Hacktoberfest

    The first 40,000 participants (maintainers and contributors) who complete Hacktoberfest can elect to receive one of two prizes: a tree planted in their name, or the Hacktoberfest 2022 t-shirt.


## Maintainers

Prepare your project for contributions by following these best practices:

* [ ] Add the “hacktoberfest” topic to your repository to opt-in to Hacktoberfest and indicate you’re looking for contributions.

* [ ] Apply the “hacktoberfest” label to issues you want contributors to help with in your GitHub or GitLab project.

* [ ] Add a CONTRIBUTING.md file with contribution guidelines to your repository.

* [ ] Choose issues that have a well-defined scope and are self-contained.

* [ ] Adopt a code of conduct to create a greater sense of inclusion and community for contributors.

* [ ] Be ready to review pull/merge requests, accepting those that are valid by merging them, leaving an overall approving review, or by adding the “hacktoberfest-accepted” label.
* [ ] Reject any spammy requests you receive by labeling them as “spam,” and any other invalid contributions by closing them or labeling them as “invalid.”

Reward for Maintainers

The hard work of our Maintainers is the reason Hacktoberfest exists, so we want you to have the opportunity to receive your very own Hacktoberfest 2022 reward. In order to become eligible for the opportunity to win a Reward Kit all a Maintainer will have to do is complete four or more maintainer actions on unique PR/MRs in repos participating in Hacktoberfest. Here are the Maintainer actions that qualify:

* [ ] Merge unique PR/MRs
* [ ] Provide an approving review of a PR/MR
* [ ] Add the “hacktoberfest-accepted” label
* [ ] Add any label with the word “invalid” or “spam”

**Comment by elreydetoda** [comment]
All that research @gerbrent did will be awesome for every time hacktoberfest comes around!

Awesome work @gerbrent 🥳🚀

**Comment by gerbrent** [comment]
Has any contributor here completed the requirements and seen benefits from participation in Hacktoberfest? Anyone?

**Comment by CGBassPlayer** [comment]
All of mine counted. You can see the badges on my GH page
