### ISSUE TITLE
add subscribe links - rss, spotify, stitcher, etc

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#66]
currently, two different styles:
* soft grey buttons on every episode
* a specific "subscribe" page w branded icons

Not sure which will be more appropriate. 

![image](https://user-images.githubusercontent.com/7018928/178120120-a37b113a-905c-49c1-b72c-46a7e18bff33.png)

## Todos
* [x] #337 
* [ ] create a main jb.com/subscribe page 
* [x] #334 
* [ ] #340

**Comment by gerbrent** [comment]
I love the idea of a consistently placed "Subscribe" link in the menu or even prominent on the page itself.

The options:

A: a unique `Subscribe` page for each sub-site/show i.e.: https://jupiterbroadcasting.net/show/coder-radio/subscribe

B: all subsites include a `Subscribe` link (in menu or body) that leads to the same page - i.e. jb . net/subscribe - that clearly outlines the options for show vs All Shows rss feeds.
* disadvantage: potentially more difficult to automate for new shows on the network.

**Comment by kd2flz** [comment]
I like option A. Curious what other people think.
________________________________

**Comment by gerbrent** [comment]
If so, we would need a strategy for the All Shows feeds too.

**Comment by StefanS-O** [comment]
I will look into it

**Comment by reesericci** [comment]
Why not just link to the podcast index?

**Comment by gerbrent** [comment]
> Why not just link to the podcast index?

Sending visitors away to perform what should be an essential function for our listeners - i.e. subscribing to the podcast(s) - shouldn't take them OFF our website. That feels like bad UX to me.. and as a new-to-JB listener might be a little odd.

That being said, most of us probably use podcast indexes of some sort via apps to browse available podcasts anyhow, but... worth placing currency in the site's user experience here regardless.

**Comment by reesericci** [comment]
That's fair - I just don't like the idea of driving traffic to spotify, sticher, etc.

**Comment by elreydetoda** [comment]
> That's fair - I just don't like the idea of driving traffic to spotify, sticher, etc.

Ya, but it's all about meeting the audience where they are (IMO) and trying to make it easy to keep them interested.

So, for example, if someone initially subscribes via Spotify, but hears Chris talking about how awesome the new podcast apps are. Then they go download one, and it’s someone that's now converted to using the podcasting 2.0 stuff, moved from Spotify, and also appreciates being informed while they were on a different platform initially.

Which they might not have even entertained if they had to copy the rrs link, paste it into their podcast player, and then start listening to the show. There's a potential to loose people at any of those steps, because people want things to be easy.


Honestly I'm one of those people, for the longest time I've stuck with castbox as my podcast app, because I could make comments with timestamps to reference different parts of the shows and keep a note for myself. I'm still on castbox but slowly migrating to Podverse, because they're supposed to support comments and a lot of other cool features. I never recommend castbox to anyone, because I don't personally even like it, but it was a critical part of how I consume podcasts and I couldn't get that feature anywhere else.

**Comment by gerbrent** [comment]
> > Why not just link to the podcast index?
> 
> Sending visitors away to perform what should be an essential function for our listeners - i.e. subscribing to the podcast(s) - shouldn't take them OFF our website. That feels like bad UX to me.. and as a new-to-JB listener might be a little odd.

To reiterate on this: Yes, we need all the links. So, adding those links to the new website is essential....

**Comment by elreydetoda** [comment]
Is there anyway we could just copy the exact text that's currently on the subscribe page? i.e. https://linuxunplugged.com/subscribe

> Subscribe
>
> Get the latest episodes of LINUX Unplugged automatically using the links above, or by copying and pasting the URL below into your favorite podcast app:
>
> LINUX UNPLUGGED RSS FEED
> 
> You can also subscribe with your favorite app directly, using the buttons below:

If so, this should be an easy single page off of each show.

The one caveat I can think of would be to ensure it doesn't show up on the episodes lists. So, we'd probably need to add a small filter on the list page template for the shows that ensures it's either an episode or excludes non-episodes.

**Comment by elreydetoda** [comment]
#291 should get us most of the way to implementing this, but I've listed to-dos for future things which'll need to be done. Also, I need someone to do the rest of the content for. I've just implemented the logic.

**Comment by elreydetoda** [comment]
Like I mentioned above someone will have to add all the data, and pasting to-dos here from PR (for ease of reading):

future to-dos:
- [ ] swap out fireside images with local ones
- [ ] create a main jb.com/subscribe page (not implemented on this one)
- [ ] add each show's subscription information
- [ ] remove/fix Google Play links (src: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/291#discussion_r946883932)
   - [ ] if removed also remove image: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/291#discussion_r946910650
- [ ] change pocket cast to new format (src: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/291#discussion_r946891639)

**Comment by elreydetoda** [comment]
Now the main thing for this issue is content for all the subscribe links. I've updated the tags to reflect that, but there is no `content` label (which might be helpful for new people to filter on). I've also created a seperate issue for future enhancements (#306)

**Comment by gerbrent** [comment]
> Is there anyway we could just copy the exact text & images that's currently on the subscribe page? i.e. https://linuxunplugged.com/subscribe
> 
> > Subscribe
> > Get the latest episodes of LINUX Unplugged automatically using the links above, or by copying and pasting the URL below into your favorite podcast app:
> > LINUX UNPLUGGED RSS FEED
> > You can also subscribe with your favorite app directly, using the buttons below:
> 
> (Don't know if this is fireside verbiage or JB verbiage, and wanted to check.)
> 


Definitely not our copy:

![image](https://user-images.githubusercontent.com/7018928/185477940-2a9c68c2-9b9e-4aa8-b2fe-c11002ebeda5.png)


; )

**Comment by hack13** [comment]
I am happy to take this on since I have already submitted a PR for #334 which is attached to this issue which would be a good pre-req for this.

**Comment by gerbrent** [comment]
@hack13 - We've flagged this as a `meta-issue`, a place for discussion and listing tasks/issues that need doing on this particular topic.

Are you suggesting you would like to be the guardian, the chaperone, the trailblazer of the entire Subscribe pages?

If so, AMAZING! If not, which task would you like to handle w the above statement?

Also - I've been digging through this Subscribe issue to clean up tasks and ideas, and am in the process of creating clean and concise todos as Issues while also testing your recent PR #336. Feel free to take any of those too as they're all related and relatively small tasks.

**Comment by hack13** [comment]
Apologies, seeing how these all seem related to the subscription page specifically. I don't mind taking on cleaning up the way people were pointing out and requesting. However, getting it more ironed out Todo List of what exactly fully agreed upon actions items are.

Which I do see you have just added to the top of this issue... But I am happy to take them one at a time, might be better since I am new to the project.

**Comment by gerbrent** [comment]
That's a mighty fine approach. I'll keep creating concise todos as issues, and you (and others) can keep picking them up in bite sized pieces. Go team!

Might I suggest #337 as a natural next place for you to enhance your current submission?

**Comment by reesericci** [comment]
Maybe we could make buttons that have the same look & feel, to create consistency, but then add the brand icon & color to the button to keep it recognizable

**Comment by gerbrent** [comment]
going to close this seemingly completed issue, with #306 tracking future Subscription-related tasks.
